# GitLab CI/CD pipeline configuration file
# See: https://docs.gitlab.com/ee/ci/yaml/README.html

default:
  image: registry.gitlab.com/smspp/bundlesolver

# This allows to cache the built libraries
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ndofioracle
    - smspp
    - milpsolver

stages:
  - build
#  - test
  - deploy

# This job is executed as first (.pre stage)
fetch_deps:
  stage: .pre
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SMSPP_DEPLOY_KEY")
    - mkdir -p ~/.ssh && ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
    # NDOFiOracle
    - if [ -d ndofioracle ]; then (cd ndofioracle && git checkout master && git pull); else git clone --branch master git@gitlab.com:frangio68/ndosolver_fioracle_project.git ndofioracle; fi
    - cmake -S ndofioracle -B ndofioracle/build -DCMAKE_BUILD_TYPE=Release
    - cmake --build ndofioracle/build
    - cmake --build ndofioracle/build --target install
    # SMS++
    - git ls-remote --heads git@gitlab.com:smspp/smspp.git ${CI_COMMIT_REF_NAME} | grep ${CI_COMMIT_REF_NAME} >/dev/null
    - if [ "$?" == "1" ]; then BRANCH_TO_USE="develop"; else BRANCH_TO_USE=${CI_COMMIT_REF_NAME}; fi; echo "Will use ${BRANCH_TO_USE} branch for SMS++"
    - if [ -d smspp ]; then (cd smspp && git checkout ${BRANCH_TO_USE} && git pull); else git clone --branch ${BRANCH_TO_USE} git@gitlab.com:smspp/smspp.git; fi
    - cmake -S smspp -B smspp/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
    - cmake --build smspp/build
    - cmake --build smspp/build --target install
    # MILPSolver
    - git ls-remote --heads git@gitlab.com:smspp/milpsolver.git ${CI_COMMIT_REF_NAME} | grep ${CI_COMMIT_REF_NAME} >/dev/null
    - if [ "$?" == "1" ]; then BRANCH_TO_USE="develop"; else BRANCH_TO_USE=${CI_COMMIT_REF_NAME}; fi; echo "Will use ${BRANCH_TO_USE} branch for MILPSolver"
    - if [ -d milpsolver ]; then (cd milpsolver && git checkout ${BRANCH_TO_USE} && git pull); else git clone --branch ${BRANCH_TO_USE} git@gitlab.com:smspp/milpsolver.git; fi
    - cmake -S milpsolver -B milpsolver/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF
    - cmake --build milpsolver/build
  only:
    refs:
      - master
      - develop
    changes:
      - cmake/*
      - BundleSolver.h
      - BundleSolver.cpp
      - CMakeLists.txt

build:
  stage: build
  before_script:
    - cmake --build ndofioracle/build --target install
    - cmake --build smspp/build --target install
    - cmake --build milpsolver/build --target install
  script:
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
  artifacts:
    paths:
      - build
  only:
    refs:
      - master
      - develop
    changes:
      - cmake/*
      - BundleSolver.h
      - BundleSolver.cpp
      - CMakeLists.txt

#test:
#  stage: test
#  before_script:
#    - cmake --build ndofioracle/build --target install
#    - cmake --build smspp/build --target install
#    - cmake --build milpsolver/build --target install
#  script:
#    - cmake --build build --target test

deploy:
  stage: deploy
  script:
    - cd build && cpack -G "TGZ;ZIP;TBZ2"
  artifacts:
    paths:
      - build/*.tar.gz
      - build/*.tar.bz2
      - build/*.zip
  only:
    - tags
